version: '3.8'

services:
  web:
    build: .
    command: gunicorn weather_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - webnet

  db:
    image: nouchka/sqlite3:latest
    container_name: weather_project_db
    volumes:
      - db_data:/app/db
    networks:
      - webnet

volumes:
  static_volume:
  db_data:

networks:
  webnet:
    driver: bridge
